// vue/src/App.vue
<template>
  <div id="app">
    <h1>Potentiaali - Vue.js</h1>

    <SkillSelection v-if="!phase" v-on:incrementPhase="incrementPhase" />
    <Questionnaire v-if="phase" :phase="phase" :questions="questions" v-on:incrementPhase="incrementPhase" />
  </div>
</template>

<script>
import SkillSelection from './components/SkillSelection';
import Questionnaire from './components/Questionnaire';

export default {
  name: 'app',
  components: {
    SkillSelection,
    Questionnaire,
  },
  data() {
    return {
      questions: [],
      phase: parseInt(localStorage.getItem('phase'), 10) || 0,
    };
  },
  created() {
    fetch('http://localhost:3000')
      .then(response => response.json())
      .then((data) => { this.questions = data; });
  },
  methods: {
    incrementPhase() {
      this.phase += 1;
      localStorage.setItem('phase', this.phase);
    },
  },
};
</script>

<style>
#app {
  display: flex;
  flex-direction: column;
  justify-content: center;
}
</style>

// react/src/App.js
import React, { Component } from 'react';

import SkillSelection from './components/SkillSelection';
import Questionnaire from './components/Questionnaire';

import './App.css';

class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      phase: parseInt(localStorage.getItem('phase'), 10) || 0,
      questions: [],
    };
  }

  componentWillMount() {
    fetch('http://localhost:3000')
      .then(response => response.json())
      .then((questions) => { this.setState({ questions }); });
  }

  incrementPhase = () => {
    const { phase } = this.state;
    this.setState({ phase: phase + 1});
    localStorage.setItem('phase', phase + 1);
  };

  render() {
    const { phase, questions } = this.state;

    return (
      <div className="App">
        <h1>Potentiaali - React</h1>

        {phase ?
          <Questionnaire
            phase={phase}
            questions={questions}
            incrementPhase={this.incrementPhase}
          /> :
          <SkillSelection
            incrementPhase={this.incrementPhase}
          />
        }
      </div>
    );
  }
}

export default App;
