// vue/src/components/Questionnaire.vue
<template>
  <div v-if="question">
    <h3>Kysymys #{{ question.id }}</h3>

    <div
      class="choice-button"
      v-for="choice in question.choices"
      @click="selectChoice(choice)"
    >
      {{ choice }}
    </div>
  </div>
</template>

<script>
export default {
  name: 'Questionnaire',
  props: ['phase', 'questions'],
  methods: {
    selectChoice(choice) {
      const base = 'http://localhost:3000';
      fetch(`${base}/answer?question=${this.question.id}&choice=${choice}`);
      this.$emit('incrementPhase');
    },
  },
  computed: {
    question() {
      return this.questions[this.phase - 1];
    },
  },
};
</script>

<style type="sass" scoped>
.choice-button {
  margin: 10px;
  padding: 10px;
  font-size: 1.5em;
  cursor: pointer;
  border: 1px solid #ccc;
}
</style>

// react/src/components/Questionnaire.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';

import './Questionnaire.css';

const propTypes = {
  incrementPhase: PropTypes.func.isRequired,
  questions: PropTypes.array.isRequired,
  phase: PropTypes.number.isRequired,
};

class Questionnaire extends Component {
  selectChoice = (choice) => {
    const { questions, phase, incrementPhase } = this.props;
    const question = questions[phase - 1];

    const base = 'http://localhost:3000';
    fetch(`${base}/answer?question=${question.id}&choice=${choice}`);

    incrementPhase();
  }

  render() {
    const { questions, phase } = this.props;
    const question = questions[phase - 1];

    if (!question) return null;

    return (
      <div className="Questionnaire">
        <h3>Kysymys #{question.id}</h3>
        {question.choices.map(choice => (
          <div
            key={choice}
            className="choice-button"
            onClick={this.selectChoice.bind(null, choice)}
          >
            {choice}
          </div>
        ))}
      </div>
    );
  }
}

Questionnaire.propTypes = propTypes;

export default Questionnaire;
